@host = http://localhost:3000
@urlMovies = /api/movies
@urlCharacters = /api/characters

############# MOVIES ###########
### GET MOVIES
GET {{host}}{{urlMovies}}

### GET ONE MOVIE
GET {{host}}{{urlMovies}}/1

###
POST {{host}}{{urlMovies}}/newMovie
Content-Type: application/json

{
    "title": "Harry Potter and the Deathly Hallows 2nd part",
    "year": "2011",
    "image": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg"
}

###
PUT {{host}}{{urlMovies}}

####
DELETE {{host}}{{urlMovies}}/12




############# Characters ###########

### GET Characters
GET {{host}}{{urlCharacters}}

### GET ONE CHARACTER
GET {{host}}{{urlCharacters}}/1

###
POST {{host}}{{urlCharacters}}/newCharacter
Content-Type: application/json

{
    "name": "Draco Malfoy",
    "type": "villain",
    "image": "https://noelialopezcheda.files.wordpress.com/2015/12/una-foto-promo-di-draco-malfoy-tom-felton-per-il-film-harry-potter-e-la-pietra-filosofale-129105.jpg?w=640",
    "status": "alive"
}

###
PUT {{host}}{{urlCharacters}}/11
Content-Type: application/json

{
    "name":"Draco Malfoy",
    "type": "villain",
    "image":"https://noelialopezcheda.files.wordpress.com/2015/12/una-foto-promo-di-draco-malfoy-tom-felton-per-il-film-harry-potter-e-la-pietra-filosofale-129105.jpg?w=640",
    "status": "alive"
}


####
DELETE {{host}}{{urlCharacters}}/10